---
# Configure postgres
#
- name: Print database location
  debug: msg="{{ db_host }}"
  tags: web

- name: Install python packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python-pip
    - python-dev
    - python3-pip
    - python3-dev
    - python-psycopg2
  tags: web

- name: Remove directory with source code
  file:
    dest: "{{ project_path }}"
    state: absent

- name: Checkout source code
  git:
    repo: 'https://github.com/icky-baker/condor/'
    dest: "{{ project_path }}"
#    version: "{{ lookup('env', 'VERSION') }}" # NOTE: this env is linux env var
    version: master
  tags: web

- name: Copy env_settings
  template:
    src: templates/env_settings.py
    dest: "{{ django_dir }}/condor"
  tags: web

- name: Install python dependencies
  pip:
    requirements: /src/app/requirements.txt
  tags: web

- name: Collectstatic
  community.general.django_manage:
    command: "collectstatic"
    project_path: "{{ django_dir }}"
  tags: web

- name: Migrate database
  community.general.django_manage:
    command: "migrate"
    project_path: "{{ django_dir }}"
  tags: web

- name: Copy supervisor config
  template:
    src: templates/condor.conf
    dest: /etc/supervisor/conf.d/condor.conf
  tags:
    - web

- name: Create directory for condor logs
  file:
    path: /var/log/condor
    state: directory
  tags: web

- name: Make sure condor service exists in supervisor
  community.general.supervisorctl:
    name: condor
    state: present
  tags: web

- name: Restart condor service
  community.general.supervisorctl:
    name: condor
    state: restarted
  tags: web
