---
# Configure postgres
#
- name: Install python packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python-pip 
    - python-dev
    - python3-pip
    - python3-dev
    - python-psycopg2
  
- name: Checkout source code
  git:
    repo: 'https://github.com/icky-baker/condor/'
    dest: "{{ project_path }}"
#    version: "{{ lookup('env', 'VERSION') }}" # NOTE: this env is linux env var
    version: master

- name: Install python dependencies
  pip:
    requirements: /src/app/requirements.txt 

- name: Collectstatic
  community.general.django_manage: 
    command: "collectstatic"
    project_path: "{{ django_dir }}"
    
- name: Migrate database
  community.general.django_manage: 
    command: "migrate"
    project_path: "{{ django_dir }}"

- name: Copy supervisor config
  template:
    src: templates/condor.conf
    dest: /etc/supervisor/conf.d/condor.conf
  
- name: Make sure condor service exists in supervisor
  community.general.supervisorctl:
    name: condor
    state: present
        
- name: Restart condor service
  community.general.supervisorctl:
    name: condor
    state: restarted