---
# Configure postgres
#
- name: Install python packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python-pip 
    - python-dev
    - python3-pip
    - python3-dev
    - python-psycopg2
  
- name: Checkout source code
  git:
    repo: 'https://github.com/icky-baker/condor/'
    dest: "{{ project_path }}"
#    version: "{{ lookup('env', 'VERSION') }}" # NOTE: this env is linux env var
    version: master

- name: Install python dependencies
  pip:
    requirements: /src/app/requirements.txt 

- name: Migrate database
  community.general.django_manage: 
    command: "migrate"
    project_path: "{{ django_dir }}"

# env for DB host
# pip install
# migrate
# wait db
# run