---

- name: Install main packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - postfix
    - bacula

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: bacula
    group: bacula
  loop:
    - /bacula
    - /bacula-restore

- name: Ensure no configuration files exist
  become: yes
  file:
    path: "{{item}}"
    state: absent
  loop:
      - /etc/bacula/bacula-dir.conf
      - /etc/bacula/bacula-fd.conf
      - /etc/bacula/bacula-sd.conf
      - /etc/bacula/bconsole.conf
      - /etc/postfix/main.cf

- name: Copy bacula configuration files
  template:
    src: templates/{{item}}
    dest: /etc/bacula/{{item}}

  loop:
    - bacula-dir.conf
    - bacula-fd.conf
    - bacula-sd.conf
    - bconsole.conf
  become: yes

- name: Copy postfix configuration files
  template:
    src: templates/main.cf
    dest: /etc/postfix/main.cf
  become: yes

- name: Restart services
  service:
    name: "{{ item }}"
    state: restarted

  loop:
    - bacula-sd
    - bacula-director
    - bacula-fd
    - postfix
