---
# Configure postgres

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: db

- name: Install PostgreSQL
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
    - python3-psycopg2
    - python-pip
    - python-dev
  tags: db

- name: Set listen_addresses to *
  lineinfile: dest=/etc/postgresql/10/main/postgresql.conf
    regexp="listen_addresses =" line="listen_addresses = '*'" state=present

  become: yes
  tags: db
  notify: restart db

- name: Set max_connection.
  lineinfile: dest=/etc/postgresql/10/main/postgresql.conf
    regexp="max_connections =" line="max_connections = 1000" state=present
  notify: restart db
  become: yes
  tags: db

- name: Copy pg_hba.conf
  template:
    src: templates/pg_hba.conf
    dest: /etc/postgresql/10/main/pg_hba.conf
  tags: db

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes
  tags: db

- name: Ensure condor database is created
  become: yes
  become_user: postgres
  community.general.postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  tags: db

- name: Create condor user
  become: yes
  become_user: postgres
  community.general.postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "ALL"
    expires: infinity
  tags: db
  notify: restart db

# just to be sure
- name: Restart Postgres
  service:
    name: postgresql
    state: restarted
  tags: db
