---
# Configure postgres

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install PostgreSQL
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
    - python3-psycopg2
    - python-pip
    - python-dev

- name: Ensure the PostgreSQL service is running
  service: 
    name: postgresql
    state: started
    enabled: yes

- name: Ensure condor database is created
  become: yes
  become_user: postgres
  community.general.postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: Create condor user
  become: yes
  become_user: postgres
  community.general.postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "ALL"
    expires: infinity
