---
# This playbook contains all actions that will be run on "local" host.

# fix issue with date difference inside VM
- name: Remove ntp
  apt:
    name: ntp
    state: absent
  become: yes
  tags:
    - setup

- name: Install ntp
  apt:
    name: ntp
    state: present
  become: yes
  tags:
    - setup

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - setup

- name: Install main packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - vim
    - net-tools
    - curl
    - supervisor
    - tree
  tags:
    - setup

# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - setup

# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - setup
