---
# This playbook contains all actions that will be run on "local" host.

# sudo apt-get update
# TODO: uncomment
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Install main packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - vim
    - net-tools
    - curl


# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system

# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system
