all:
  hosts:
    server1:
      ansible_connection: ssh
      ansible_user: serv # Remote user
      ansible_host: "{{ip1}}"
      ansible_port: 22

    server2:
      ansible_connection: ssh
      ansible_user: serv # Remote user
      ansible_host: "{{ip2}}"
      ansible_port: 22

    server3:
      ansible_connection: ssh
      ansible_user: serv # Remote user
      ansible_host: "{{ip3}}"
      ansible_port: 22
