---
# This playbook sets up whole stack.

- name: Configurations to "remote" host
  hosts: test
  remote_user: serv # Remote user
#  become_user: postgres
  become: yes
  vars_files:
    - host_vars/main

  roles:
#      - setup
#      - db
      - web
