---
# This playbook sets up whole stack.

- name: Setup configuration
  hosts:
    - server1
    - server2
  become: yes
  vars_files:
    - host_vars/main

  roles:
      - setup

- name: Database configuration
  hosts:
    - server1
#    - server2
  become: yes
  vars_files:
    - host_vars/main

  roles:
    - db

- name: Web configuration
  hosts:
    - server1
    - server2
  become: yes
  vars_files:
    - host_vars/main
  environment:
    db_host: '{{ db_host }}'

  roles:
    - web
